project:
  type: website

website:
  title: "MJER Iaido Dortmund"
  site-url: "https://www.iaido-dortmund.de"
  description: "Traditionelle japanische Schwertkampfkunst Iaido in Dortmund"
  search:
    location: sidebar
  sidebar:
    style: "docked"
    pinned: true
    search: true
    contents:
      - index.qmd
      - blog.qmd
      - training.qmd
      - about.qmd
    tools:
      - icon: facebook
        href: https://www.facebook.com/profile.php?id=61552009765748
      - icon: instagram
        href: https://www.instagram.com/eishinryuiaidodortmund/
      - icon: github
        href: https://github.com/RichardMeyer-Eppler/iaido-dortmund
      - icon: rss
        href: blog.xml

lang: de
        
format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

