project:
  type: website
  output-dir: docs

website:
  title: "MJER Iaido Dortmund"
  sidebar:
    style: "docked"
    pinned: true
    search: true
    contents:
      - section: "Basics"
        contents:
          - index.qmd
          - about.qmd
          - blog.qmd
          
format:
  html:
    theme: darkly
    css: styles.css
    toc: true

editor: visual

