---
title: "Home"
lang: de
---

Herzlich willkommen auf den Webseiten des Dortmunder Dojos für die traditionelle japanische Schwertkampfkunst Iaido!

Im Iaido werden feste Bewegungsformen einstudiert, die mit Schwert und größtenteils ohne Partner trainiert werden.
Das Training übt Körperbeherrschung und Selbstwahrnehmung und führt zu einer intensiven Beschäftigung mit den eigenen mentalen und körperlichen Grenzen.
Die in Dortmund trainierte Stilrichtung ist das *Muso Jikiden Eishin Ryu*, das vor 450 Jahren in Japan entstanden ist.
Der Stil wurde ununterbrochen bis in die Gegenwart von Lehrer zu Schüler weitergegeben.

::: callout-caution
Die Webseite ist im Aufbau befindlich und ändert sich derzeit noch häufig!
:::

National sind wir Mitglied des [Muso Jikiden Eishin Ryu Verband Deutschland e.V.](www.iaidoverband.org). Zusätzlich sind wir direkte Mitglieder des internationalen Dachverbandes [Ippan Shadanhōjin Seitō Seiryu Muso Jikiden Eishin Ryu Iaido](https://mjer-iaido.github.io/en/) (kurz Kokusai Renmei) unter Leitung von Kobara Kenichi Sensei, Hanshi.
